{% set name = "aif360" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a03b3a61fa6a912ede3cc75724a95b4ab06695e500f957527da0dfc40d664f5d

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - matplotlib-base
    - numpy >=1.16
    - pandas >=0.24.0
    - pip
    - python >=3.6
    - scikit-learn >=0.22.1
    - scipy >=1.2.0,<1.6.0
    - tempeh
  run:
    - matplotlib-base
    - numpy >=1.16
    - pandas >=0.24.0
    - python >=3.6
    - scikit-learn >=0.22.1
    - scipy >=1.2.0,<1.6.0
    - tempeh

test:
  imports:
    - aif360

about:
  home: https://github.com/Trusted-AI/AIF360
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: IBM AI Fairness 360
  doc_url: https://aif360.mybluemix.net/
  dev_url: https://github.com/Trusted-AI/AIF360

extra:
  recipe-maintainers:
    - philip-khor
