{% set name = "aif360" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 635afc0bbe785e08fa242eee5e5080238193d0583bc0f5006a132050d4fb77f2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy >=1.16
    - scipy >=1.2.0
    - pandas >=0.24.0
    - scikit-learn >=1.0
    - matplotlib-base

test:
  imports:
    - aif360

about:
  home: https://github.com/Trusted-AI/AIF360
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: IBM AI Fairness 360
  doc_url: https://aif360.mybluemix.net/
  dev_url: https://github.com/Trusted-AI/AIF360

extra:
  recipe-maintainers:
    - ZanMervic
    - philip-khor
    - primozgodec
